name = "SmoothSpline"
uuid = "68d5d808-f842-4b98-8c06-98eacef18d29"
authors = ["Robert Dahl Jacobsen <git@dahl-jacobsen.dk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
RCall = "0.13"
julia = "1.5"

[extras]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "RCall", "Test"]
